CREATE TABLE base_pay_channel_config (
    f_id varchar(50) NOT NULL,
    f_creator_time datetime,
    f_creator_user_id varchar(50),
    f_last_modify_time datetime,
    f_last_modify_user_id varchar(50),
    f_delete_mark int,
    f_delete_time datetime,
    f_delete_user_id varchar(50),
    f_description varchar(512),
    f_pay_app_code varchar(64),
    f_pay_app_name varchar(128),
    f_channel_code varchar(32),
    f_merchant_id varchar(128),
    f_app_id varchar(128),
    f_environment varchar(32),
    f_notify_url varchar(512),
    f_refund_notify_url varchar(512),
    f_config_json text,
    f_enabled_mark int,
    f_sort_code bigint,
    PRIMARY KEY (f_id)
);

CREATE TABLE base_pay_order (
    f_id varchar(50) NOT NULL,
    f_creator_time datetime,
    f_creator_user_id varchar(50),
    f_last_modify_time datetime,
    f_last_modify_user_id varchar(50),
    f_delete_mark int,
    f_delete_time datetime,
    f_delete_user_id varchar(50),
    f_description varchar(512),
    f_pay_order_no varchar(64),
    f_biz_type varchar(64),
    f_ref_table varchar(128),
    f_ref_value varchar(64),
    f_ref_no varchar(128),
    f_pay_app_code varchar(64),
    f_channel_code varchar(32),
    f_subject varchar(256),
    f_body varchar(512),
    f_total_amount bigint,
    f_paid_amount bigint,
    f_refund_amount bigint,
    f_currency varchar(16),
    f_order_status varchar(32),
    f_pay_scene varchar(32),
    f_client_ip varchar(64),
    f_open_id varchar(128),
    f_expire_time datetime,
    f_pay_time datetime,
    f_close_time datetime,
    f_channel_trade_no varchar(128),
    f_channel_order_no varchar(128),
    f_extra_json text,
    PRIMARY KEY (f_id)
);

CREATE TABLE base_pay_order_item (
    f_id varchar(50) NOT NULL,
    f_creator_time datetime,
    f_creator_user_id varchar(50),
    f_last_modify_time datetime,
    f_last_modify_user_id varchar(50),
    f_delete_mark int,
    f_delete_time datetime,
    f_delete_user_id varchar(50),
    f_description varchar(512),
    f_pay_order_id varchar(50),
    f_pay_order_no varchar(64),
    f_biz_type varchar(64),
    f_ref_table varchar(128),
    f_ref_value varchar(64),
    f_ref_no varchar(128),
    f_item_name varchar(256),
    f_item_amount bigint,
    f_paid_amount bigint,
    f_refund_amount bigint,
    f_item_status varchar(32),
    f_extra_json text,
    PRIMARY KEY (f_id)
);

CREATE TABLE base_pay_transaction (
    f_id varchar(50) NOT NULL,
    f_creator_time datetime,
    f_creator_user_id varchar(50),
    f_last_modify_time datetime,
    f_last_modify_user_id varchar(50),
    f_delete_mark int,
    f_delete_time datetime,
    f_delete_user_id varchar(50),
    f_description varchar(512),
    f_pay_order_id varchar(50),
    f_pay_order_no varchar(64),
    f_transaction_no varchar(64),
    f_channel_code varchar(32),
    f_trade_type varchar(32),
    f_trade_status varchar(32),
    f_amount bigint,
    f_channel_trade_no varchar(128),
    f_request_body text,
    f_response_body text,
    f_error_code varchar(128),
    f_error_message varchar(512),
    f_request_time datetime,
    f_response_time datetime,
    PRIMARY KEY (f_id)
);

CREATE TABLE base_pay_refund_order (
    f_id varchar(50) NOT NULL,
    f_creator_time datetime,
    f_creator_user_id varchar(50),
    f_last_modify_time datetime,
    f_last_modify_user_id varchar(50),
    f_delete_mark int,
    f_delete_time datetime,
    f_delete_user_id varchar(50),
    f_description varchar(512),
    f_refund_no varchar(64),
    f_pay_order_id varchar(50),
    f_pay_order_no varchar(64),
    f_biz_type varchar(64),
    f_ref_table varchar(128),
    f_ref_value varchar(64),
    f_ref_no varchar(128),
    f_channel_code varchar(32),
    f_refund_amount bigint,
    f_refund_reason varchar(512),
    f_refund_status varchar(32),
    f_channel_refund_no varchar(128),
    f_refund_time datetime,
    f_extra_json text,
    PRIMARY KEY (f_id)
);

CREATE TABLE base_pay_refund_item (
    f_id varchar(50) NOT NULL,
    f_creator_time datetime,
    f_creator_user_id varchar(50),
    f_last_modify_time datetime,
    f_last_modify_user_id varchar(50),
    f_delete_mark int,
    f_delete_time datetime,
    f_delete_user_id varchar(50),
    f_description varchar(512),
    f_refund_order_id varchar(50),
    f_refund_no varchar(64),
    f_pay_order_item_id varchar(50),
    f_ref_table varchar(128),
    f_ref_value varchar(64),
    f_ref_no varchar(128),
    f_refund_amount bigint,
    f_refund_status varchar(32),
    f_extra_json text,
    PRIMARY KEY (f_id)
);

CREATE TABLE base_pay_notify_record (
    f_id varchar(50) NOT NULL,
    f_creator_time datetime,
    f_creator_user_id varchar(50),
    f_last_modify_time datetime,
    f_last_modify_user_id varchar(50),
    f_delete_mark int,
    f_delete_time datetime,
    f_delete_user_id varchar(50),
    f_description varchar(512),
    f_notify_no varchar(64),
    f_notify_type varchar(32),
    f_channel_code varchar(32),
    f_pay_order_no varchar(64),
    f_refund_no varchar(64),
    f_channel_notify_id varchar(128),
    f_channel_trade_no varchar(128),
    f_notify_status varchar(32),
    f_verify_status varchar(32),
    f_business_status varchar(32),
    f_notify_body text,
    f_response_body varchar(512),
    f_error_message varchar(1024),
    f_notify_time datetime,
    f_handle_time datetime,
    f_retry_count int,
    PRIMARY KEY (f_id)
);

CREATE TABLE base_pay_status_record (
    f_id varchar(50) NOT NULL,
    f_creator_time datetime,
    f_creator_user_id varchar(50),
    f_last_modify_time datetime,
    f_last_modify_user_id varchar(50),
    f_delete_mark int,
    f_delete_time datetime,
    f_delete_user_id varchar(50),
    f_description varchar(512),
    f_object_type varchar(32),
    f_object_id varchar(50),
    f_object_no varchar(64),
    f_before_status varchar(32),
    f_after_status varchar(32),
    f_change_type varchar(32),
    f_change_reason varchar(512),
    f_operator_type varchar(32),
    f_operator_id varchar(50),
    f_extra_json text,
    PRIMARY KEY (f_id)
);
